### ISSUE TITLE
DEPRECATION WARNING: alias_method_chain is deprecated (Ruby 2.3.1 / Rails 5)

### ISSUE THREAD

**Issue by Gedrovits** [ishumilova/before_render#1]
`
DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from block in <module:BeforeRenderInstance> at /Users/vgedrovits/.rvm/gems/ruby-2.3.1/bundler/gems/before_render-bce4678a6e00/lib/before_render/before_render_instance.rb:6)
`

**Comment by ishumilova** [comment]
resolved
